
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class BridgeForm extends javax.swing.JFrame
{
   private BufferedImage image;
   private ArrayList<Shape> ShgapeList=new ArrayList<>();
   private ShapeBridgeImage sbImage=new ShapeBridgeImage(null);
   private DefaultListModel<String> lbmodel=new DefaultListModel<>();

   public BridgeForm()
   {
      initComponents();
      lbShapeList.setModel(lbmodel);
      cbShapeKind.removeAllItems();
      for(String kind:ShapeFactory.keySet()) cbShapeKind.addItem(kind);
      resizeImage();
      sbImage.proceed(ShgapeList);
      repaint();
   }

   private void resizeImage()
   {
      image=new BufferedImage(pnImageBox.getWidth(),pnImageBox.getHeight(),BufferedImage.TYPE_4BYTE_ABGR);
      sbImage.setImage(image);
   }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      pnData = new javax.swing.JPanel();
      cbShapeKind = new javax.swing.JComboBox<>();
      tfShapeParemeters = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      lbShapeList = new javax.swing.JList<>();
      btnAdd = new javax.swing.JButton();
      pnText = new javax.swing.JPanel();
      pnImageBox = new ImageBox(null);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      cbShapeKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kind" }));

      tfShapeParemeters.setText("60,60;50");

      lbShapeList.setModel(new javax.swing.AbstractListModel<String>()
      {
         String[] strings = { "list" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(lbShapeList);

      btnAdd.setText("Dodaj");
      btnAdd.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnAddActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout pnDataLayout = new javax.swing.GroupLayout(pnData);
      pnData.setLayout(pnDataLayout);
      pnDataLayout.setHorizontalGroup(
         pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(pnDataLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(tfShapeParemeters)
               .addGroup(pnDataLayout.createSequentialGroup()
                  .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(cbShapeKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnAdd))
                  .addGap(0, 165, Short.MAX_VALUE)))
            .addContainerGap())
      );
      pnDataLayout.setVerticalGroup(
         pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(pnDataLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(cbShapeKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfShapeParemeters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnAdd)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addContainerGap())
      );

      javax.swing.GroupLayout pnTextLayout = new javax.swing.GroupLayout(pnText);
      pnText.setLayout(pnTextLayout);
      pnTextLayout.setHorizontalGroup(
         pnTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      pnTextLayout.setVerticalGroup(
         pnTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 161, Short.MAX_VALUE)
      );

      pnImageBox.addComponentListener(new java.awt.event.ComponentAdapter()
      {
         public void componentResized(java.awt.event.ComponentEvent evt)
         {
            pnImageBoxComponentResized(evt);
         }
      });

      javax.swing.GroupLayout pnImageBoxLayout = new javax.swing.GroupLayout(pnImageBox);
      pnImageBox.setLayout(pnImageBoxLayout);
      pnImageBoxLayout.setHorizontalGroup(
         pnImageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 543, Short.MAX_VALUE)
      );
      pnImageBoxLayout.setVerticalGroup(
         pnImageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(pnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(pnImageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(pnText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(pnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(pnImageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void pnImageBoxComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_pnImageBoxComponentResized
   {//GEN-HEADEREND:event_pnImageBoxComponentResized
      resizeImage();
      ((ImageBox)pnImageBox).setImage(image);
   }//GEN-LAST:event_pnImageBoxComponentResized

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
   {//GEN-HEADEREND:event_btnAddActionPerformed
      try
      {
         Shape shape=ShapeFactory.make(cbShapeKind.getSelectedItem().toString(),tfShapeParemeters.getText());
         ShgapeList.add(shape);
         sbImage.proceed(ShgapeList);
         repaint();
      }
      catch(Exception e)
      {
         tfShapeParemeters.selectAll();
         tfShapeParemeters.requestFocus();
      }
   }//GEN-LAST:event_btnAddActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            if("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
      }
      catch(ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(BridgeForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(BridgeForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(BridgeForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(BridgeForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new BridgeForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdd;
   private javax.swing.JComboBox<String> cbShapeKind;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JList<String> lbShapeList;
   private javax.swing.JPanel pnData;
   private javax.swing.JPanel pnImageBox;
   private javax.swing.JPanel pnText;
   private javax.swing.JTextField tfShapeParemeters;
   // End of variables declaration//GEN-END:variables
}
