-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-02-22 20:03:48 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



DROP TABLE bd4_klient CASCADE CONSTRAINTS;

DROP TABLE bd4_produkt CASCADE CONSTRAINTS;

DROP TABLE bd4_rachunek CASCADE CONSTRAINTS;

DROP SEQUENCE seq_klient;

DROP SEQUENCE seq_rachunek;
