
INSERT INTO BD4_KLIENT (NR_KLIENTA, KLIENT_NAZWISKO, KLIENT_IMIE, KLIENT_ADRES, KLIENT_MIASTO, KLIENT_KOD_ADRESOWY) 
VALUES (SEQ_KLIENT.NEXTVAL, 'Abacki', 'Adam', 'ul. Piêkna 16/20', 'Warszawa', '02-876');

INSERT INTO BD4_KLIENT (NR_KLIENTA, KLIENT_NAZWISKO, KLIENT_IMIE, KLIENT_ADRES, KLIENT_MIASTO, KLIENT_KOD_ADRESOWY) 
VALUES (SEQ_KLIENT.NEXTVAL, 'Babacki', 'Bogdan', 'ul. Kwiatowa 1', 'Kraków', '31-475');

INSERT INTO BD4_KLIENT (NR_KLIENTA, KLIENT_NAZWISKO, KLIENT_IMIE, KLIENT_ADRES, KLIENT_MIASTO, KLIENT_KOD_ADRESOWY) 
VALUES (SEQ_KLIENT.NEXTVAL, 'Cabacki', 'Czes³aw', 'ul. Strumieniowa 34/65', 'Warszawa', '02-876');

------------------------------------------

INSERT INTO BD4_PRODUKT (NR_PRODUKTU, NAZWA_PRODUKTU, CENA_PRODUKTU, ROK_PRODUKCJI, RANKING) 
VALUES (3021, 'Canon 6D Body', 4450, 2016, 8);

INSERT INTO BD4_PRODUKT (NR_PRODUKTU, NAZWA_PRODUKTU, CENA_PRODUKTU, ROK_PRODUKCJI, RANKING) 
VALUES (3055, 'Obiektyw EF 50mm', 519.99, 2012, null);

INSERT INTO BD4_PRODUKT (NR_PRODUKTU, NAZWA_PRODUKTU, CENA_PRODUKTU, ROK_PRODUKCJI, RANKING) 
VALUES (4265, 'Obiektyw EF 24-105mm', 669, 2015, 6 );

INSERT INTO BD4_PRODUKT (NR_PRODUKTU, NAZWA_PRODUKTU, CENA_PRODUKTU, ROK_PRODUKCJI, RANKING) 
VALUES (4268, 'Obiektyw EF 70-200mm', 3649, 2014, null );

-----------------------------------------
INSERT INTO BD4_RACHUNEK (DATA_SPRZEDAZY, ILOSC_PRODUKTU, NR_PRODUKTU, NR_KLIENTA) 
VALUES ('2018/09/20', 4, 3021, 100);

INSERT INTO BD4_RACHUNEK (DATA_SPRZEDAZY, ILOSC_PRODUKTU, NR_PRODUKTU, NR_KLIENTA) 
VALUES ('2018/10/05', 2, 3055, 110);

INSERT INTO BD4_RACHUNEK (DATA_SPRZEDAZY, ILOSC_PRODUKTU, NR_PRODUKTU, NR_KLIENTA) 
VALUES ('2018/09/20', 3, 4268, 100);

------------------------------------------

COMMIT;