
import java.util.HashMap;
import javax.swing.JButton;

public class Calculator extends javax.swing.JFrame {

   private boolean NeedReset=true;
   private double SaveValue=0,OldValue=0;
   private String Operation=null,OldOperation=null;
   private final HashMap<String,JButton> btnmap=new HashMap<>();   
   private static final HashMap<String,OperationClass> map=makemap();
   private static final HashMap<String,OperationClass> makemap()
   {
      final HashMap<String,OperationClass> tmp=new HashMap<>();
      tmp.put("+", (double a,double b) -> { return a+b; } );
      tmp.put("-", (double a,double b) -> { return a-b; } );
      tmp.put("*", (double a,double b) -> { return a*b; } );
      tmp.put("/", new OperationClass() { @Override public double exec(double a,double b) { return a/b; } } );
      return tmp;
   }
   
   public Calculator() {
      initComponents();
      btnmap.put("0", BtnDig0);
      btnmap.put("1", BtnDig1);
      btnmap.put("2", BtnDig2);
      btnmap.put("3", BtnDig3);
      btnmap.put("4", BtnDig4);
      btnmap.put("5", BtnDig5);
      btnmap.put("6", BtnDig6);
      btnmap.put("7", BtnDig7);
      btnmap.put("8", BtnDig8);
      btnmap.put("9", BtnDig9);
      btnmap.put("+", BtnOprAdd);
      btnmap.put("-", BtnOprSub);
      btnmap.put("*", BtnOprMul);
      btnmap.put("/", BtnOprDiv);
      btnmap.put(".", BtnPoint);
      btnmap.put(",", BtnPoint);
      btnmap.put("\b", BtnFuncCE);
      btnmap.put(""+(char)127, BtnFuncC);
      btnmap.put("=", BtnResult);
      btnmap.put("\n", BtnResult);
      EDisplay.requestFocus();      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      EDisplay = new javax.swing.JTextField();
      BtnFuncCE = new javax.swing.JButton();
      BtnDig7 = new javax.swing.JButton();
      BtnDig8 = new javax.swing.JButton();
      BtnDig9 = new javax.swing.JButton();
      BtnFuncC = new javax.swing.JButton();
      BtnDig4 = new javax.swing.JButton();
      BtnDig5 = new javax.swing.JButton();
      BtnDig6 = new javax.swing.JButton();
      BtnOprAdd = new javax.swing.JButton();
      BtnOprSub = new javax.swing.JButton();
      BtnDig1 = new javax.swing.JButton();
      BtnDig2 = new javax.swing.JButton();
      BtnDig3 = new javax.swing.JButton();
      BtnOprMul = new javax.swing.JButton();
      BtnOprDiv = new javax.swing.JButton();
      BtnPoint = new javax.swing.JButton();
      BtnDig0 = new javax.swing.JButton();
      BtnResult = new javax.swing.JButton();
      BtnParOp = new javax.swing.JButton();
      BtnParCl = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      EDisplay.setEditable(false);
      EDisplay.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
      EDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      EDisplay.setText("0");
      EDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            EDisplayKeyPressed(evt);
         }
      });

      BtnFuncCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnFuncCE.setText("CE");
      BtnFuncCE.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnFuncCEActionPerformed(evt);
         }
      });

      BtnDig7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig7.setText("7");
      BtnDig7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig8.setText("8");
      BtnDig8.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig9.setText("9");
      BtnDig9.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnFuncC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnFuncC.setText("C");
      BtnFuncC.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnFuncCActionPerformed(evt);
         }
      });

      BtnDig4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig4.setText("4");
      BtnDig4.setToolTipText("");
      BtnDig4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig5.setText("5");
      BtnDig5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig6.setText("6");
      BtnDig6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnOprAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnOprAdd.setText("+");
      BtnOprAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnOprActionPerformed(evt);
         }
      });

      BtnOprSub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnOprSub.setText("-");
      BtnOprSub.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnOprActionPerformed(evt);
         }
      });

      BtnDig1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig1.setText("1");
      BtnDig1.setToolTipText("");
      BtnDig1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig2.setText("2");
      BtnDig2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnDig3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig3.setText("3");
      BtnDig3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnOprMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnOprMul.setText("*");
      BtnOprMul.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnOprActionPerformed(evt);
         }
      });

      BtnOprDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnOprDiv.setText("/");
      BtnOprDiv.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnOprActionPerformed(evt);
         }
      });

      BtnPoint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnPoint.setText(".");
      BtnPoint.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnPointActionPerformed(evt);
         }
      });

      BtnDig0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnDig0.setText("0");
      BtnDig0.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDigActionPerformed(evt);
         }
      });

      BtnResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnResult.setText("=");
      BtnResult.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnResultActionPerformed(evt);
         }
      });

      BtnParOp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnParOp.setText("(");

      BtnParCl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      BtnParCl.setText(")");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(EDisplay)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDig7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BtnDig8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDig9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnFuncCE, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnFuncC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDig4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BtnDig5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDig6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOprAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOprSub, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDig1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BtnDig2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDig3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOprMul, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOprDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(BtnDig0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnParOp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnParCl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(EDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnDig7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnFuncCE, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnFuncC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnDig4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnOprAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnOprSub, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnDig1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnOprMul, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnOprDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnDig0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnParOp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnParCl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
 
   private void DoCalculate(String nextOperation)
   {
      double CurrValue;
      if(NeedReset&&(nextOperation==null)) CurrValue=OldValue;
      else CurrValue=Double.parseDouble(EDisplay.getText());
      if((Operation==null)&&(nextOperation==null)) Operation=OldOperation;
      if(map.containsKey(Operation))
      {
         OldValue=CurrValue;
         CurrValue=map.get(Operation).exec(SaveValue, CurrValue);
         EDisplay.setText(String.format("%s",CurrValue).replace(",","."));
      }
      NeedReset=true;
      SaveValue=CurrValue;
      Operation=nextOperation;
      if(nextOperation!=null) OldOperation=Operation;
   }
   
   private void BtnDigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDigActionPerformed
      JButton btn=(JButton)evt.getSource();
      EDisplay.setText((NeedReset?"":EDisplay.getText())+btn.getText());
      NeedReset=false;
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnDigActionPerformed

   private void BtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPointActionPerformed
      EDisplay.setText((NeedReset?"0":EDisplay.getText()).replace(".","")+".");
      NeedReset=false;
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnPointActionPerformed

   private void BtnOprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOprActionPerformed
      DoCalculate(((JButton)evt.getSource()).getText());
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnOprActionPerformed

   private void BtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResultActionPerformed
      DoCalculate(null);
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnResultActionPerformed

   private void BtnFuncCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFuncCEActionPerformed
      if(!NeedReset)
      {
         String text=EDisplay.getText();
         int len=text.length();
         if(len>0) EDisplay.setText(text.substring(0,len-1));
      }
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnFuncCEActionPerformed

   private void BtnFuncCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFuncCActionPerformed
      NeedReset=true;
      SaveValue=OldValue=0;
      Operation=null;
      EDisplay.setText("0");
      EDisplay.requestFocus();
   }//GEN-LAST:event_BtnFuncCActionPerformed

   private void EDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDisplayKeyPressed
      String str=""+evt.getKeyChar();
      if(btnmap.containsKey(str)) btnmap.get(str).doClick(100);
      EDisplay.requestFocus();
   }//GEN-LAST:event_EDisplayKeyPressed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Calculator().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnDig0;
   private javax.swing.JButton BtnDig1;
   private javax.swing.JButton BtnDig2;
   private javax.swing.JButton BtnDig3;
   private javax.swing.JButton BtnDig4;
   private javax.swing.JButton BtnDig5;
   private javax.swing.JButton BtnDig6;
   private javax.swing.JButton BtnDig7;
   private javax.swing.JButton BtnDig8;
   private javax.swing.JButton BtnDig9;
   private javax.swing.JButton BtnFuncC;
   private javax.swing.JButton BtnFuncCE;
   private javax.swing.JButton BtnOprAdd;
   private javax.swing.JButton BtnOprDiv;
   private javax.swing.JButton BtnOprMul;
   private javax.swing.JButton BtnOprSub;
   private javax.swing.JButton BtnParCl;
   private javax.swing.JButton BtnParOp;
   private javax.swing.JButton BtnPoint;
   private javax.swing.JButton BtnResult;
   private javax.swing.JTextField EDisplay;
   // End of variables declaration//GEN-END:variables
}

interface OperationClass
{
   double exec(double a,double b);
}