
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import jumpStrategy.IJump;
import jumpStrategy.JumpManager;
import runStrategy.IRun;
import runStrategy.RunManager;
import swimStrategy.ISwim;
import swimStrategy.SwimManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class CommandForm extends javax.swing.JFrame {

   private DefaultListModel<Command> model=new DefaultListModel<>();
   private DefaultListModel<Command> content=new DefaultListModel<>();
   private DefaultComboBoxModel<String> modelSwim = new DefaultComboBoxModel<>();
   private DefaultComboBoxModel<String> modelRun = new DefaultComboBoxModel<>();
   private DefaultComboBoxModel<String> modelJump = new DefaultComboBoxModel<>();
   
   public CommandForm() {
      initComponents();
      CommandList.setModel(model);
      model.addElement(new Run());
      model.addElement(new Swim());
      model.addElement(new Jump());
      TreningList.setModel(content);
      CommandList.requestFocus();
      getRootPane().setDefaultButton(BtnExecuteCommand);
      
      for (String key : JumpManager.keys()) {
         modelJump.addElement(key);
      }
      for (String key : SwimManager.keys()) {
         modelSwim.addElement(key);
      }
      for (String key : RunManager.keys()) {
         modelRun.addElement(key);
      }
      
      run.setModel(modelRun);
      swim.setModel(modelSwim);
      jump.setModel(modelJump);
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      CommandListScroller = new javax.swing.JScrollPane();
      CommandList = new javax.swing.JList<>();
      TreningListScroller = new javax.swing.JScrollPane();
      TreningList = new javax.swing.JList<>();
      TreningName = new javax.swing.JTextField();
      BtnAddItem = new javax.swing.JButton();
      BtnMakeCommand = new javax.swing.JButton();
      Log = new java.awt.TextArea();
      BtnExecuteCommand = new javax.swing.JButton();
      BtnRemoveCommand = new javax.swing.JButton();
      swim = new javax.swing.JComboBox<>();
      run = new javax.swing.JComboBox<>();
      jump = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      CommandList.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            CommandListMouseClicked(evt);
         }
      });
      CommandListScroller.setViewportView(CommandList);

      TreningListScroller.setViewportView(TreningList);

      TreningName.setText("New");

      BtnAddItem.setText("=>");
      BtnAddItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnAddItemActionPerformed(evt);
         }
      });

      BtnMakeCommand.setText("<=");
      BtnMakeCommand.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnMakeCommandActionPerformed(evt);
         }
      });

      BtnExecuteCommand.setText("Execute");
      BtnExecuteCommand.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnExecuteCommandActionPerformed(evt);
         }
      });

      BtnRemoveCommand.setText("Remove");
      BtnRemoveCommand.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnRemoveCommandActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(Log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(CommandListScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(BtnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(BtnMakeCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(BtnExecuteCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                     .addComponent(BtnRemoveCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(swim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(run, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jump, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(TreningName)
                     .addComponent(TreningListScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(TreningName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(BtnAddItem))
                  .addGap(11, 11, 11)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnMakeCommand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRemoveCommand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnExecuteCommand))
                     .addComponent(TreningListScroller, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
               .addComponent(CommandListScroller))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddItemActionPerformed
      int index=CommandList.getSelectedIndex();
      Command cmd=model.elementAt(index);
      content.addElement(cmd);
      CommandList.requestFocus();
   }//GEN-LAST:event_BtnAddItemActionPerformed

   private void BtnMakeCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMakeCommandActionPerformed
      String name=TreningName.getText().trim();
      Command[] list=new Command[content.size()];
      for(int i=0;i<content.size();++i) list[i]=content.get(i);
      model.addElement(new Trening(name,list));
      CommandList.setSelectedIndex(model.size()-1);
      content.clear();
      CommandList.requestFocus();
   }//GEN-LAST:event_BtnMakeCommandActionPerformed

   private void BtnRemoveCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveCommandActionPerformed
      int index=CommandList.getSelectedIndex();
      if(index>=3) model.remove(index);
      CommandList.requestFocus();
   }//GEN-LAST:event_BtnRemoveCommandActionPerformed

   private void BtnExecuteCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExecuteCommandActionPerformed
      int index=CommandList.getSelectedIndex();
      Command cmd=model.elementAt(index);
      ISwim _swim = SwimManager.make(swim.getSelectedItem().toString());
      IRun _run = RunManager.make(run.getSelectedItem().toString());
      IJump _jump = JumpManager.make(jump.getSelectedItem().toString());
      Log.append(cmd.execute(new Sportsman(_swim, _jump, _run))+"\n");
      CommandList.requestFocus();
   }//GEN-LAST:event_BtnExecuteCommandActionPerformed

   private void CommandListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommandListMouseClicked
      if(evt.getClickCount()==2)
      {
         int index=CommandList.getSelectedIndex();
         Command tr=model.elementAt(index);
         TreningName.setText(tr.name());
         content.clear();
         if(tr instanceof Trening)
         {
            for(Command cmd:((Trening)tr).getList()) content.addElement(cmd);
         }
         TreningName.requestFocus();
      }
   }//GEN-LAST:event_CommandListMouseClicked

   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(CommandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(CommandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(CommandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(CommandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new CommandForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAddItem;
   private javax.swing.JButton BtnExecuteCommand;
   private javax.swing.JButton BtnMakeCommand;
   private javax.swing.JButton BtnRemoveCommand;
   private javax.swing.JList<Command> CommandList;
   private javax.swing.JScrollPane CommandListScroller;
   private java.awt.TextArea Log;
   private javax.swing.JList<Command> TreningList;
   private javax.swing.JScrollPane TreningListScroller;
   private javax.swing.JTextField TreningName;
   private javax.swing.JComboBox<String> jump;
   private javax.swing.JComboBox<String> run;
   private javax.swing.JComboBox<String> swim;
   // End of variables declaration//GEN-END:variables
}
