
import java.awt.EventQueue;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class HarmCalc extends javax.swing.JFrame
{
   private long count;
   public HarmCalc()
   {
      initComponents();
      getRootPane().setDefaultButton(BtnCalc);
      DocumentListener listener=new DocumentListener()
      {
         @Override public void insertUpdate(DocumentEvent e) { EdCountChanged(e); }
         @Override public void removeUpdate(DocumentEvent e) { EdCountChanged(e); }
         @Override public void changedUpdate(DocumentEvent e) { EdCountChanged(e); }
      };
      EdCount.getDocument().addDocumentListener(listener);
      EdCount.setText("1000000000");
   }

    public void EdCountChanged(DocumentEvent e)
    {
       try
       {
          count=Long.parseLong(EdCount.getText());
          BtnCalc.setEnabled(true);
       }
       catch(NumberFormatException ex)
       {
          BtnCalc.setEnabled(false);
       }
    }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      EdCount = new javax.swing.JTextField();
      BtnCalc = new javax.swing.JButton();
      EdResultScroll = new javax.swing.JScrollPane();
      EdResult = new javax.swing.JTextArea();
      BtnThread = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      EdCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

      BtnCalc.setText("Licz");
      BtnCalc.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnCalcActionPerformed(evt);
         }
      });

      EdResult.setEditable(false);
      EdResult.setColumns(20);
      EdResult.setRows(5);
      EdResultScroll.setViewportView(EdResult);

      BtnThread.setText("Wątek");
      BtnThread.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnThreadActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(EdResultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(EdCount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnCalc)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(BtnThread)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EdCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnCalc)
               .addComponent(BtnThread))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(EdResultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private double calc(long count)
   {
      double sum=0;
      for(long i=1;i<=count;++i) sum+=1D/i;
      return sum;
   }

   private void execute(long count)
   {
      EdResult.append(String.format("%d -> %.13f",count,calc(count))+System.lineSeparator());
   }

   private void BtnCalcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCalcActionPerformed
   {//GEN-HEADEREND:event_BtnCalcActionPerformed
      EdResult.selectAll();
      EdResult.requestFocus();
      new Thread(() -> execute(count)).start();
   }//GEN-LAST:event_BtnCalcActionPerformed

   private void ThreadRun()
   {
      for(int i=0;i<=10;++i)
      {
         EdResult.append(String.format("%d%%",10*i)+System.lineSeparator());
         try { Thread.sleep(1000); }
         catch(Exception ex) {}
      }
   }

   private void BtnThreadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnThreadActionPerformed
   {//GEN-HEADEREND:event_BtnThreadActionPerformed
      /*
      Runnable run=new Runnable()
      {
         @Override public void run()
         {
            ThreadRun();
         }
      };
      new Thread(run).start();
      new Thread(() ->  ThreadRun()).start();
      */
      new Thread(this::ThreadRun).start();
   }//GEN-LAST:event_BtnThreadActionPerformed

   static void wykonaj(Runnable x)
   {
      x.run();
   }

   public static void start()
   {
      new HarmCalc().setVisible(true);
   }

   public static void main(String args[])
   {
      /*
      EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            start();
         }
      });
      */
      /*
      Runnable run=new Runnable()
      {
         public void run()
         {
            start();
         }
      };
      EventQueue.invokeLater(run);
      */
      /*
      EventQueue.invokeLater(() -> start());
      */
      java.awt.EventQueue.invokeLater(HarmCalc::start);
      /*
      */
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnCalc;
   private javax.swing.JButton BtnThread;
   private javax.swing.JTextField EdCount;
   private javax.swing.JTextArea EdResult;
   private javax.swing.JScrollPane EdResultScroll;
   // End of variables declaration//GEN-END:variables
}

class MyException extends Exception
{
   public MyException() {}
}