
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class BaseControl extends javax.swing.JFrame
{

   private DefaultListModel<RowForList> ModelOfRows=new DefaultListModel<>();
   public BaseControl()
   {
      initComponents();
      LbOfRows.setModel(ModelOfRows);
      DocumentListener listener=new DocumentListener()
      {
         @Override public void insertUpdate(DocumentEvent e) { check(e); }
         @Override public void removeUpdate(DocumentEvent e) { check(e); }
         @Override public void changedUpdate(DocumentEvent e) { check(e); }
         public void check(DocumentEvent e)
         {
            BtnAdd.setEnabled
            (
               EdText.getText().trim().length()>0
                  &&
               Integer.getInteger(EdValue.getText())!=null
            );
         }
      };
      EdText.getDocument().addDocumentListener(listener);
      EdValue.getDocument().addDocumentListener(listener);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      LbOfRowsScroll = new javax.swing.JScrollPane();
      LbOfRows = new javax.swing.JList<>();
      EdText = new javax.swing.JTextField();
      EdValue = new javax.swing.JTextField();
      BtnAdd = new javax.swing.JButton();
      BtnRemove = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      LbOfRowsScroll.setViewportView(LbOfRows);

      EdValue.setText("10");

      BtnAdd.setText("Dodaj");
      BtnAdd.setEnabled(false);
      BtnAdd.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnAddActionPerformed(evt);
         }
      });

      BtnRemove.setText("Usuń");
      BtnRemove.setEnabled(false);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(EdText)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(EdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(LbOfRowsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(BtnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(BtnRemove, javax.swing.GroupLayout.Alignment.TRAILING))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(BtnRemove)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(LbOfRowsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(EdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnAdd))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnAddActionPerformed
   {//GEN-HEADEREND:event_BtnAddActionPerformed
      ModelOfRows.addElement(new RowForList(EdText.getText(),Integer.getInteger(EdValue.getText())));
   }//GEN-LAST:event_BtnAddActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            if("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
      }
      catch(ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(BaseControl.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(BaseControl.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(BaseControl.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(BaseControl.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new BaseControl().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAdd;
   private javax.swing.JButton BtnRemove;
   private javax.swing.JTextField EdText;
   private javax.swing.JTextField EdValue;
   private javax.swing.JList<RowForList> LbOfRows;
   private javax.swing.JScrollPane LbOfRowsScroll;
   // End of variables declaration//GEN-END:variables
}

class RowForList
{
   private String name;
   private int value;

   public RowForList(String str,int value)
   {
      this.name=str;
      this.value=value;
   }

   public String getStr()
   {
      return name;
   }

   public void setStr(String str)
   {
      this.name=str;
   }

   public int getValue()
   {
      return value;
   }

   public void setValue(int value)
   {
      this.value=value;
   }

   @Override public String toString()
   {
      return String.format("%s: %d",name,value);
   }
}