
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class MatrixOperationForm extends javax.swing.JFrame
{
   /**
    * Creates new form MatrixOperationForm
    */
   public MatrixOperationForm()
   {
      initComponents();
      PropertyChangeListener listener=new PropertyChangeListener()
      {
         @Override public void propertyChange(PropertyChangeEvent evt)
         {
            if(evt.getSource()==SpLeft)
            {
               SpRight.setDividerLocation(SpLeft.getDividerLocation());
            }
            else if(evt.getSource()==SpRight)
            {
               SpLeft.setDividerLocation(SpRight.getDividerLocation());
            }
         }
      };
      SpLeft.addPropertyChangeListener(SpLeft.LAST_DIVIDER_LOCATION_PROPERTY,listener);
      SpRight.addPropertyChangeListener(SpRight.LAST_DIVIDER_LOCATION_PROPERTY,listener);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      SpVertical = new javax.swing.JSplitPane();
      jSplitPane2 = new javax.swing.JSplitPane();
      jSplitPane3 = new javax.swing.JSplitPane();
      SpLeft = new javax.swing.JSplitPane();
      jPanel1 = new javax.swing.JPanel();
      BtnAdd = new javax.swing.JButton();
      BtnSub = new javax.swing.JButton();
      Mul = new javax.swing.JButton();
      BtnSolve = new javax.swing.JButton();
      BtnInv = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      TaMatrixA = new javax.swing.JTextArea();
      SpRight = new javax.swing.JSplitPane();
      jScrollPane2 = new javax.swing.JScrollPane();
      TaMatrixB = new javax.swing.JTextArea();
      jScrollPane3 = new javax.swing.JScrollPane();
      TaMatrixResult = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      SpVertical.setDividerLocation(350);
      SpVertical.setDividerSize(8);

      jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
      SpVertical.setLeftComponent(jSplitPane2);

      jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
      SpVertical.setLeftComponent(jSplitPane3);

      SpLeft.setDividerLocation(200);
      SpLeft.setDividerSize(8);
      SpLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

      BtnAdd.setText("Add");
      BtnAdd.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnAddActionPerformed(evt);
         }
      });

      BtnSub.setText("Sub");

      Mul.setText("Mul");

      BtnSolve.setText("Solve");

      BtnInv.setText("Inv");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(BtnAdd)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnSub)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(Mul))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(BtnInv)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnSolve)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnAdd)
               .addComponent(BtnSub)
               .addComponent(Mul))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnInv)
               .addComponent(BtnSolve))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      SpLeft.setTopComponent(jPanel1);

      TaMatrixA.setColumns(20);
      TaMatrixA.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
      TaMatrixA.setRows(5);
      TaMatrixA.setText("8\t3.5\t6.8\n2\t8\t4.8\n1.6\t2.5\t5.9\n");
      jScrollPane1.setViewportView(TaMatrixA);

      SpLeft.setRightComponent(jScrollPane1);

      SpVertical.setLeftComponent(SpLeft);

      SpRight.setDividerLocation(200);
      SpRight.setDividerSize(8);
      SpRight.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

      TaMatrixB.setColumns(20);
      TaMatrixB.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
      TaMatrixB.setRows(5);
      TaMatrixB.setText("7.3\t1\t8.8\n0.6\t5.3\t1.7\n1.8\t8\t6.2\n");
      jScrollPane2.setViewportView(TaMatrixB);

      SpRight.setLeftComponent(jScrollPane2);

      TaMatrixResult.setEditable(false);
      TaMatrixResult.setBackground(java.awt.SystemColor.controlHighlight);
      TaMatrixResult.setColumns(20);
      TaMatrixResult.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
      TaMatrixResult.setRows(5);
      jScrollPane3.setViewportView(TaMatrixResult);

      SpRight.setRightComponent(jScrollPane3);

      SpVertical.setRightComponent(SpRight);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(SpVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(SpVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnAddActionPerformed
   {//GEN-HEADEREND:event_BtnAddActionPerformed
      //Matrix a=Matrix.parse(TaMatrixA.getText());
      //Matrix b=Matrix.parse(TaMatrixB.getText());
      //Matrix r=Matrix.add(a,b);
      //TaMatrixResult.setText(r.toString());
   }//GEN-LAST:event_BtnAddActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            if("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
      }
      catch(ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new MatrixOperationForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAdd;
   private javax.swing.JButton BtnInv;
   private javax.swing.JButton BtnSolve;
   private javax.swing.JButton BtnSub;
   private javax.swing.JButton Mul;
   private javax.swing.JSplitPane SpLeft;
   private javax.swing.JSplitPane SpRight;
   private javax.swing.JSplitPane SpVertical;
   private javax.swing.JTextArea TaMatrixA;
   private javax.swing.JTextArea TaMatrixB;
   private javax.swing.JTextArea TaMatrixResult;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JSplitPane jSplitPane2;
   private javax.swing.JSplitPane jSplitPane3;
   // End of variables declaration//GEN-END:variables
}
