
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

public class BuyList extends javax.swing.JFrame {

   final IterableListModel<Food> model = new IterableListModel<Food>();
   
   public BuyList() {
      initComponents();
      ListBox.setModel(model);
      ListBox.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      getRootPane().setDefaultButton(BtnAdd);
      KeyListener kb=new KeyListener()
      {
         @Override public void keyPressed(KeyEvent e) { formKeyPressed(e); }
         @Override public void keyTyped(KeyEvent e) {}
         @Override public void keyReleased(KeyEvent e) {}
      };
      ListBox.addKeyListener(kb);
      TxtName.addKeyListener(kb);
      BtnAdd.addKeyListener(kb);
      BtnDel.addKeyListener(kb);
      TxtName.requestFocus();
      ListDataListener data=new ListDataListener()
      {
         @Override public void intervalAdded(ListDataEvent e) { changed(); }
         @Override public void intervalRemoved(ListDataEvent e) { changed(); }
         @Override public void contentsChanged(ListDataEvent e)  { changed(); }
      };
      model.addListDataListener(data);
   }

   void changed()
   {
      long sum=0;
      /*/// to jest poczatek bloku alternatywnego
      for(int i=0;i<model.getSize();++i)
      {
         sum+=model.get(i).getValue();
      }  
      /*/
      for(Food food : model) sum+=food.getValue();
      //*/// to jest koniec bloku alternatywnego
      txtSum.setText(String.format("%.2f", 0.01 * sum));
   }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      ListScroll = new javax.swing.JScrollPane();
      ListBox = new javax.swing.JList<>();
      TxtName = new javax.swing.JTextField();
      BtnAdd = new javax.swing.JButton();
      BtnDel = new javax.swing.JButton();
      TxtPrice = new javax.swing.JTextField();
      txtSum = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            formKeyPressed(evt);
         }
      });

      ListBox.setToolTipText("");
      ListScroll.setViewportView(ListBox);

      BtnAdd.setText("Add");
      BtnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnAddActionPerformed(evt);
         }
      });

      BtnDel.setText("Delete");
      BtnDel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnDelActionPerformed(evt);
         }
      });

      TxtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      TxtPrice.setText("0");
      TxtPrice.setPreferredSize(new java.awt.Dimension(60, 20));

      txtSum.setEditable(false);
      txtSum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtSum.setText("0");
      txtSum.setPreferredSize(new java.awt.Dimension(60, 20));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(ListScroll)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDel)
                        .addGap(193, 193, 193)))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(TxtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(ListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(TxtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnAdd)
               .addComponent(BtnDel)
               .addComponent(txtSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
      String name=TxtName.getText();
      long count=1000;
      long price=Math.round(100*Double.parseDouble(TxtPrice.getText().replace(",",".")));
      Food food = new Food(name,count,price);
      model.addElement(food);
      ListBox.setSelectedIndex(model.getSize()-1);
      TxtName.selectAll();
      TxtName.requestFocus();
   }//GEN-LAST:event_BtnAddActionPerformed

   private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
      int idx=ListBox.getSelectedIndex();
      if(idx>=0) model.remove(idx);
      ListBox.setSelectedIndex(ListBox.getLeadSelectionIndex());
      ListBox.requestFocus();
   }//GEN-LAST:event_BtnDelActionPerformed

   private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_DELETE && evt.isControlDown())
      {
         BtnDel.doClick();
      }
   }//GEN-LAST:event_formKeyPressed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(BuyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(BuyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(BuyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(BuyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new BuyList().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAdd;
   private javax.swing.JButton BtnDel;
   private javax.swing.JList<Food> ListBox;
   private javax.swing.JScrollPane ListScroll;
   private javax.swing.JTextField TxtName;
   private javax.swing.JTextField TxtPrice;
   private javax.swing.JTextField txtSum;
   // End of variables declaration//GEN-END:variables
}
