
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

public class CommandTestForm extends javax.swing.JFrame 
{
   private final DefaultListModel<Command> CommandsModel=new DefaultListModel<>();
   private final DefaultListModel<Command> TreningModel=new DefaultListModel<>();
   public CommandTestForm() 
   {
      initComponents();
      CommandsModel.addElement(new CommandSwim());
      CommandsModel.addElement(new CommandJump());
      CommandsModel.addElement(new CommandRun());
      LbCommands.setModel(CommandsModel);
      LbTrening.setModel(TreningModel);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      LbCommansScroll = new javax.swing.JScrollPane();
      LbTrening = new javax.swing.JList<>();
      LbTreningScroll = new javax.swing.JScrollPane();
      LbCommands = new javax.swing.JList<>();
      BtnAddToTrening = new javax.swing.JButton();
      BtnMakeCommand = new javax.swing.JButton();
      EdTreningName = new javax.swing.JTextField();
      LogScroll = new javax.swing.JScrollPane();
      Log = new javax.swing.JTextArea();
      EdName = new javax.swing.JTextField();
      BtnExecute = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      LbCommansScroll.setViewportView(LbTrening);

      LbCommands.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            LbCommandsMouseClicked(evt);
         }
      });
      LbTreningScroll.setViewportView(LbCommands);

      BtnAddToTrening.setText("Add =>");
      BtnAddToTrening.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnAddToTreningActionPerformed(evt);
         }
      });

      BtnMakeCommand.setText("<= Insert");
      BtnMakeCommand.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnMakeCommandActionPerformed(evt);
         }
      });

      EdTreningName.setText("Trening");

      Log.setEditable(false);
      Log.setColumns(20);
      Log.setRows(5);
      LogScroll.setViewportView(Log);

      EdName.setText("Kowalski");

      BtnExecute.setText("Execute");
      BtnExecute.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnExecuteActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(LogScroll)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(LbTreningScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                     .addComponent(EdName))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnExecute)
                        .addGap(0, 0, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(BtnAddToTrening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(BtnMakeCommand)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(EdTreningName, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbCommansScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(LbTreningScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(LbCommansScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(BtnAddToTrening)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(BtnMakeCommand)
                     .addComponent(EdTreningName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnExecute))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(LogScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnAddToTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddToTreningActionPerformed
      final Command cmd=LbCommands.getSelectedValue();
      TreningModel.addElement(cmd);
      LbCommands.requestFocus();
   }//GEN-LAST:event_BtnAddToTreningActionPerformed

   private void BtnMakeCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMakeCommandActionPerformed
      final String name=EdTreningName.getText();
      final ArrayList<Command> lst=new ArrayList<>();
      for(int i=0;i<TreningModel.size();++i) lst.add(TreningModel.get(i));
      final Command cmd=new CommandTrening(name,lst);
      TreningModel.clear();
      CommandsModel.addElement(cmd);
      LbCommands.requestFocus();
   }//GEN-LAST:event_BtnMakeCommandActionPerformed

   private void BtnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExecuteActionPerformed
      final Command cmd=LbCommands.getSelectedValue();
      final Sportsmen sp=new Sportsmen(EdName.getText());
      Log.append(sp.execute(cmd)+System.lineSeparator());
   }//GEN-LAST:event_BtnExecuteActionPerformed

   private void LbCommandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCommandsMouseClicked
      if(evt.getClickCount()==2)
      {
         final Command cmd=LbCommands.getSelectedValue();
         if(cmd instanceof CommandTrening)
         {
            TreningModel.clear();
            final ArrayList<Command> lst=((CommandTrening)cmd).getList();
            for(Command item:lst)
            {
               TreningModel.addElement(item);
            }
         }
      }
      LbCommands.requestFocus();
   }//GEN-LAST:event_LbCommandsMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(CommandTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(CommandTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(CommandTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(CommandTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new CommandTestForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAddToTrening;
   private javax.swing.JButton BtnExecute;
   private javax.swing.JButton BtnMakeCommand;
   private javax.swing.JTextField EdName;
   private javax.swing.JTextField EdTreningName;
   private javax.swing.JList<Command> LbCommands;
   private javax.swing.JScrollPane LbCommansScroll;
   private javax.swing.JList<Command> LbTrening;
   private javax.swing.JScrollPane LbTreningScroll;
   private javax.swing.JTextArea Log;
   private javax.swing.JScrollPane LogScroll;
   // End of variables declaration//GEN-END:variables
}
