-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-11-10 13:14:21 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



DROP TABLE bd5_faktura_detale CASCADE CONSTRAINTS;

DROP TABLE bd5_faktura_naglowek CASCADE CONSTRAINTS;

DROP TABLE bd5_klient CASCADE CONSTRAINTS;

DROP TABLE bd5_produkt CASCADE CONSTRAINTS;

DROP SEQUENCE bd5_faktura_seq;

DROP SEQUENCE bd5_klient_seq;

