/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test012;

import javax.swing.SpinnerListModel;

/**
 *
 * @author alex
 */
public class ParamForm extends javax.swing.JDialog {

    Test012 main;
    /**
     * Creates new form ParamForm
     */
    public ParamForm(Test012 amain) {
        main = amain;
        initComponents();
        MatrixSize.setValue(""+main.getMatrixSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MatrixSize = new javax.swing.JSpinner();

        MatrixSize.setModel(new javax.swing.SpinnerListModel(new String[] {"2", "3", "4", "5", "6", "7", "8"}));
        MatrixSize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MatrixSize.setEditor(new javax.swing.JSpinner.ListEditor(MatrixSize));
        MatrixSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MatrixSizeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getMatrixSize()
    {
        return Math.max(2,Math.min(8,Integer.parseInt((String)MatrixSize.getValue())));
    }
    
    private void MatrixSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MatrixSizeStateChanged
        main.setMatrixSize(getMatrixSize());
    }//GEN-LAST:event_MatrixSizeStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner MatrixSize;
    // End of variables declaration//GEN-END:variables
}
