import java.awt.TextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class HarmCalc extends javax.swing.JFrame
{
   private long count;
   public HarmCalc()
   {
      initComponents();
      getRootPane().setDefaultButton(BtnCalc);
      /*
      DocumentListener listener=new DocumentListener()
      {
         @Override public void insertUpdate(DocumentEvent e) { EdCountChanged(e); }
         @Override public void removeUpdate(DocumentEvent e) { EdCountChanged(e); }
         @Override public void changedUpdate(DocumentEvent e) { EdCountChanged(e); }
      };
      EdCount.getDocument().addDocumentListener(listener);
      */
      DocumentListener listener=new DocumentListener()
      {
         @Override public void insertUpdate(DocumentEvent e) { EdCountChange(e); }
         @Override public void removeUpdate(DocumentEvent e) { EdCountChange(e); }
         @Override public void changedUpdate(DocumentEvent e) { EdCountChange(e); }
      };
      EdCount.getDocument().addDocumentListener(listener);
      EdCount.setText("1000000000");
   }

   private void EdCountChange(DocumentEvent e)
   {
      try
      {
         count=Long.parseLong(EdCount.getText());
         BtnCalc.setEnabled(true);
      }
      catch(Exception ex)
      {
         BtnCalc.setEnabled(false);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      EdCount = new javax.swing.JTextField();
      BtnCalc = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      EdResult = new javax.swing.JTextArea();
      BtnTread = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      EdCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

      BtnCalc.setText("Licz");
      BtnCalc.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnCalcActionPerformed(evt);
         }
      });

      EdResult.setEditable(false);
      EdResult.setColumns(20);
      EdResult.setRows(5);
      jScrollPane1.setViewportView(EdResult);

      BtnTread.setText("Watek");
      BtnTread.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnTreadActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(EdCount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnCalc)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                  .addComponent(BtnTread)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EdCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnCalc)
               .addComponent(BtnTread))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private static double calculate(long count)
   {
      double sum=0;
      for(long i=1;i<=count;++i) sum+=1D/i;
      return sum;
   }

   private void execute()
   {
      EdResult.append(String.format("%d -> %.13f",count,calculate(count))+System.lineSeparator());
   }

   private void BtnCalcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCalcActionPerformed
   {//GEN-HEADEREND:event_BtnCalcActionPerformed
      EdCount.selectAll();
      EdCount.requestFocus();
      new Thread(() -> execute()).start();
   }//GEN-LAST:event_BtnCalcActionPerformed

   private void ThreadRun()
   {
      for(int i=1;i<=10;++i)
      {
         EdResult.append(String.format("%d%%",10*i)+System.lineSeparator());
         try { Thread.sleep(1000); }
         catch(Exception ex) {}
      }
   }

   private void BtnTreadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnTreadActionPerformed
   {//GEN-HEADEREND:event_BtnTreadActionPerformed
      /*
      Runnable run=new Runnable()
      {
         @Override public void run(int x)
         {
            ThreadRun();
         }
      };
      new Thread(run).start();
      new Thread(this::ThreadRun).start();
      */
      new Thread(()->ThreadRun()).start();
   }//GEN-LAST:event_BtnTreadActionPerformed

   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(() -> new HarmCalc().setVisible(true));
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnCalc;
   private javax.swing.JButton BtnTread;
   private javax.swing.JTextField EdCount;
   private javax.swing.JTextArea EdResult;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
