import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.TreeMap;
import javax.swing.JTextArea;

public class Semigraphics extends javax.swing.JFrame {

   public Semigraphics() {
      initComponents();
      getRootPane().setDefaultButton(BtnExecute);
      for(String item : map.keySet()) Kind.addItem(item);
      EdHeight.selectAll();
      EdHeight.requestFocus();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      LblHeight = new javax.swing.JLabel();
      EdHeight = new javax.swing.JTextField();
      BtnExecute = new javax.swing.JButton();
      LblResult = new javax.swing.JLabel();
      ScrollResult = new javax.swing.JScrollPane();
      TextResult = new javax.swing.JTextArea();
      Kind = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      LblHeight.setText("Wysokość");

      EdHeight.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
      EdHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      EdHeight.setText("5");
      EdHeight.setPreferredSize(new java.awt.Dimension(60, 25));

      BtnExecute.setText("Wykonaj");
      BtnExecute.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnExecuteActionPerformed(evt);
         }
      });

      LblResult.setText("Wynik");

      TextResult.setColumns(20);
      TextResult.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
      TextResult.setRows(5);
      ScrollResult.setViewportView(TextResult);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ScrollResult)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(EdHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(Kind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                  .addComponent(BtnExecute))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(LblHeight)
                     .addComponent(LblResult))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(LblHeight)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(EdHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(BtnExecute)
               .addComponent(Kind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(LblResult)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ScrollResult, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private static TreeMap<String,Checker> map=makeMap();   
   private static TreeMap<String,Checker> makeMap()
   {
      TreeMap<String,Checker> map=new TreeMap<String,Checker>();
      map.put
      (
         "Left Down",
         new Checker()
         {
            @Override public boolean check(int x,int y,int height)
            {
               return (x<=y); 
            }
         }
      );
      map.put
      (
         "Left Up",
         new Checker()
         {
            @Override public boolean check(int x,int y,int height)
            {
               return (x<=height-y-1); 
            }
         }
      );
      map.put
      (
         "Right Down",
         new Checker()
         {
            @Override public boolean check(int x,int y,int height)
            {
               return (height-x-1<=y); 
            }
         }
      );
      map.put
      (
         "Right Up",
         new Checker()
         {
            @Override public boolean check(int x,int y,int height)
            {
               return (height-x-1<=height-y-1); 
            }
         }
      );
      map.put
      (
         "Diamond",
         new Checker()
         {
            @Override public boolean check(int x,int y,int height)
            {
               return (Math.abs(2*x-height+1)+Math.abs(2*y-height+1)<=height); 
            }
         }
      );
      return map;
   }
   
   private void BtnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExecuteActionPerformed
      TextResult.setText("");
      int height=Integer.parseInt(EdHeight.getText());
      Checker chk=map.get(Kind.getSelectedItem().toString());
      for(int y=0;y<height;++y)
      {
         for(int x=0;x<height;++x)
         {
            TextResult.append(chk.check(x, y, height)?"*":" ");
         }
         TextResult.append("\n");
      }
      EdHeight.selectAll();
      EdHeight.requestFocus();
   }//GEN-LAST:event_BtnExecuteActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Semigraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Semigraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Semigraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Semigraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Semigraphics().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnExecute;
   private javax.swing.JTextField EdHeight;
   private javax.swing.JComboBox<String> Kind;
   private javax.swing.JLabel LblHeight;
   private javax.swing.JLabel LblResult;
   private javax.swing.JScrollPane ScrollResult;
   private javax.swing.JTextArea TextResult;
   // End of variables declaration//GEN-END:variables
}
