/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrixoperation;

/**
 *
 * @author alex
 */
public class MatrixOperationMainForm extends javax.swing.JFrame
{

   /**
    * Creates new form MatrixOperationMainForm
    */
   public MatrixOperationMainForm()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      SpHorizontal = new javax.swing.JSplitPane();
      SpLeft = new javax.swing.JSplitPane();
      jScrollPane1 = new javax.swing.JScrollPane();
      TaMatrixA = new javax.swing.JTextArea();
      PnButtons = new javax.swing.JPanel();
      BtnTest = new javax.swing.JButton();
      BtnAdd = new javax.swing.JButton();
      BtnSub = new javax.swing.JButton();
      BtnSolve = new javax.swing.JButton();
      BtnInv = new javax.swing.JButton();
      SpRight = new javax.swing.JSplitPane();
      jScrollPane2 = new javax.swing.JScrollPane();
      TaMatrixB = new javax.swing.JTextArea();
      jScrollPane3 = new javax.swing.JScrollPane();
      TaMatrixResult = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      SpHorizontal.setDividerLocation(350);
      SpHorizontal.setDividerSize(8);

      SpLeft.setDividerLocation(220);
      SpLeft.setDividerSize(8);
      SpLeft.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
      SpLeft.addPropertyChangeListener(new java.beans.PropertyChangeListener()
      {
         public void propertyChange(java.beans.PropertyChangeEvent evt)
         {
            SpLeftPropertyChange(evt);
         }
      });

      TaMatrixA.setColumns(20);
      TaMatrixA.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
      TaMatrixA.setRows(5);
      jScrollPane1.setViewportView(TaMatrixA);

      SpLeft.setBottomComponent(jScrollPane1);

      BtnTest.setText("Test");
      BtnTest.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnTestActionPerformed(evt);
         }
      });

      BtnAdd.setText("Add");

      BtnSub.setText("Sub");

      BtnSolve.setText("Solve");

      BtnInv.setText("Inv");

      javax.swing.GroupLayout PnButtonsLayout = new javax.swing.GroupLayout(PnButtons);
      PnButtons.setLayout(PnButtonsLayout);
      PnButtonsLayout.setHorizontalGroup(
         PnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(PnButtonsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(PnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(BtnTest)
               .addGroup(PnButtonsLayout.createSequentialGroup()
                  .addComponent(BtnAdd)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnSub))
               .addGroup(PnButtonsLayout.createSequentialGroup()
                  .addComponent(BtnSolve)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(BtnInv)))
            .addContainerGap(223, Short.MAX_VALUE))
      );
      PnButtonsLayout.setVerticalGroup(
         PnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(PnButtonsLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(BtnTest)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnAdd)
               .addComponent(BtnSub))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(BtnSolve)
               .addComponent(BtnInv))
            .addContainerGap(127, Short.MAX_VALUE))
      );

      SpLeft.setLeftComponent(PnButtons);

      SpHorizontal.setLeftComponent(SpLeft);

      SpRight.setDividerLocation(221);
      SpRight.setDividerSize(8);
      SpRight.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
      SpRight.addPropertyChangeListener(new java.beans.PropertyChangeListener()
      {
         public void propertyChange(java.beans.PropertyChangeEvent evt)
         {
            SpRightPropertyChange(evt);
         }
      });

      TaMatrixB.setColumns(20);
      TaMatrixB.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
      TaMatrixB.setRows(5);
      jScrollPane2.setViewportView(TaMatrixB);

      SpRight.setTopComponent(jScrollPane2);

      TaMatrixResult.setEditable(false);
      TaMatrixResult.setBackground(new java.awt.Color(204, 204, 204));
      TaMatrixResult.setColumns(20);
      TaMatrixResult.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
      TaMatrixResult.setRows(5);
      jScrollPane3.setViewportView(TaMatrixResult);

      SpRight.setRightComponent(jScrollPane3);

      SpHorizontal.setRightComponent(SpRight);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(SpHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(SpHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnTestActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnTestActionPerformed
   {//GEN-HEADEREND:event_BtnTestActionPerformed
      //Matrix a=Matrix.parseMatrix(TaMatrixA.getText());
      //Matrix b=Matrix.parseMatrix(TaMatrixB.getText());
      //TaMatrixResult.setText(Matrix.add(a,b).toString());
   }//GEN-LAST:event_BtnTestActionPerformed

   private void SpRightPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_SpRightPropertyChange
   {//GEN-HEADEREND:event_SpRightPropertyChange
      if(evt.getPropertyName().equals("dividerLocation"))
      {
         SpLeft.setDividerLocation(SpRight.getDividerLocation());
      }
   }//GEN-LAST:event_SpRightPropertyChange

   private void SpLeftPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_SpLeftPropertyChange
   {//GEN-HEADEREND:event_SpLeftPropertyChange
      if(evt.getPropertyName().equals("dividerLocation"))
      {
         SpRight.setDividerLocation(SpLeft.getDividerLocation());
      }
   }//GEN-LAST:event_SpLeftPropertyChange

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            if("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
      }
      catch(ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationMainForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationMainForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationMainForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(MatrixOperationMainForm.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new MatrixOperationMainForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnAdd;
   private javax.swing.JButton BtnInv;
   private javax.swing.JButton BtnSolve;
   private javax.swing.JButton BtnSub;
   private javax.swing.JButton BtnTest;
   private javax.swing.JPanel PnButtons;
   private javax.swing.JSplitPane SpHorizontal;
   private javax.swing.JSplitPane SpLeft;
   private javax.swing.JSplitPane SpRight;
   private javax.swing.JTextArea TaMatrixA;
   private javax.swing.JTextArea TaMatrixB;
   private javax.swing.JTextArea TaMatrixResult;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   // End of variables declaration//GEN-END:variables
}
