import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class MatrixTest extends javax.swing.JFrame
{

   public MatrixTest()
   {
      initComponents();
      DocumentListener dl=new DocumentListener()
      {
        @Override public void removeUpdate(DocumentEvent e) { textChanged(); }
        @Override public void insertUpdate(DocumentEvent e) { textChanged(); }
        @Override public void changedUpdate(DocumentEvent e) { textChanged(); }
      };
      MatLf.getDocument().addDocumentListener(dl);
      textChanged();
   }
   
   public void textChanged()
   {
      try
      {
         Matrix mat = new Matrix(MatLf.getText());
         MatRt.setText(mat.inv().toString());
         Info.setText("");
      }
      catch(Exception e)
      {
         MatRt.setText("");
         Info.setText(e.getMessage());
      }
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      MatLfScroll = new javax.swing.JScrollPane();
      MatLf = new javax.swing.JTextPane();
      MatRtScroll = new javax.swing.JScrollPane();
      MatRt = new javax.swing.JTextPane();
      InfoScroll = new javax.swing.JScrollPane();
      Info = new javax.swing.JTextPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      MatLf.setText("3\t2\t6\t7\n9\t1\t9\t9\n7\t8\t3\t7\n4\t5\t5\t3\n");
      MatLfScroll.setViewportView(MatLf);

      MatRt.setEditable(false);
      MatRtScroll.setViewportView(MatRt);

      Info.setEditable(false);
      InfoScroll.setViewportView(Info);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(MatLfScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(MatRtScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
         .addComponent(InfoScroll)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(MatRtScroll)
               .addComponent(MatLfScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(InfoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MatrixTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MatrixTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MatrixTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MatrixTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MatrixTest().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextPane Info;
   private javax.swing.JScrollPane InfoScroll;
   private javax.swing.JTextPane MatLf;
   private javax.swing.JScrollPane MatLfScroll;
   private javax.swing.JTextPane MatRt;
   private javax.swing.JScrollPane MatRtScroll;
   // End of variables declaration//GEN-END:variables
}
