#!/bin/sh
zmienna=`snmpwalk -v 1 localhost -c public .1.3.6.1.4.1.2021.10 | grep Flag.1 | cut -d' ' -f 4`
sprawdz="noError(0)"
if [ "$zmienna" = "noError(0)" ]
then
exit 0 
else 
snmptrap -v 2c -c public localhost 6000 1.3.6.1.4.1.11.2.17.1.0.1001 1.3.6.1.4.1.11.2.17.1.0.1002 s "jest zle"
fi
