/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex
 */
public class ImageProcessorMain extends javax.swing.JFrame
{

   /**
    * Creates new form ImageProcessorMain
    */
   public ImageProcessorMain()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPane1 = new javax.swing.JScrollPane();
      Mask = new javax.swing.JTextArea();
      BtnStart = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      Mask.setColumns(20);
      Mask.setRows(5);
      Mask.setText("  -1, -1, -1, -1, -1;\n  -1,  2,  2,  2, -1;\n  -1,  2,  8,  2, -1;\n  -1,  2,  2,  2, -1;\n  -1, -1, -1, -1, -1");
      jScrollPane1.setViewportView(Mask);

      BtnStart.setText("Start");
      BtnStart.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            BtnStartActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(BtnStart)
            .addContainerGap(146, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(BtnStart)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(185, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnStartActionPerformed
   {//GEN-HEADEREND:event_BtnStartActionPerformed
      String[] rows=Mask.getText().trim().split(";");
      String[][] cols=new String[rows.length][];
      double mask[][]=new double[rows.length][];
      for(int y=0;y<cols.length;++y)
      {
         cols[y]=rows[y].trim().split(",");
         mask[y]=new double[cols[y].length];
         for(int x=0;x<cols[y].length;++x)
         {
            mask[y][x]=Double.parseDouble(cols[y][x].trim());
         }
      }
      try
      {
         byte[][][] clr=ImageHelper.LoadImage("P:\\Barski\\POJ\\2018_z\\ImageProcessorTest\\Flower.png");
         ImageHelper.SaveImage("P:\\Barski\\POJ\\2018_z\\ImageProcessorTest\\test.png",clr);
         ImageProcessor ip=new ImageProcessor(mask);
         byte[][][] dst=ip.proceed(clr);
         ImageHelper.SaveImage("P:\\Barski\\POJ\\2018_z\\ImageProcessorTest\\out.png",dst);
      }
      catch(Exception e) {}
   }//GEN-LAST:event_BtnStartActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try
      {
         for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            if("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
      }
      catch(ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(ImageProcessorMain.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(ImageProcessorMain.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(ImageProcessorMain.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      catch(javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(ImageProcessorMain.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new ImageProcessorMain().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnStart;
   private javax.swing.JTextArea Mask;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
