-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-02-20 15:42:40 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2


CREATE TABLE bd3_kategorie (
    nr_kategorii     NUMBER(2) NOT NULL,
    nazwa_kategorii  VARCHAR2(6) NOT NULL,
    dolny_prog       NUMBER(4) NOT NULL,
    gorny_prog       NUMBER(4) NOT NULL
);

CREATE UNIQUE INDEX pk_bd3_kategorie ON
    bd3_kategorie (nr_kategorii);

ALTER TABLE bd3_kategorie
    ADD CONSTRAINT pk_bd3_kategorie PRIMARY KEY ( nr_kategorii )
        USING INDEX pk_bd3_kategorie;

CREATE TABLE bd3_kluby (
    nr_klubu     NUMBER(3) NOT NULL,
    nazwa_klubu  VARCHAR2(40)
);

CREATE UNIQUE INDEX pk_bd3_kluby ON
    bd3_kluby (nr_klubu);

ALTER TABLE bd3_kluby
    ADD CONSTRAINT pk_bd3_kluby PRIMARY KEY ( nr_klubu )
        USING INDEX pk_bd3_kluby;

CREATE TABLE bd3_wyniki (
    nr_zawodow         NUMBER(2) NOT NULL,
    nr_zawodnika       NUMBER(4) NOT NULL,
    rezultat_min       NUMBER(3) NOT NULL,
    rezultat_sek       NUMBER(2) NOT NULL,
    pozycja            NUMBER(1) DEFAULT 1 NOT NULL,
    punkty_globalne    NUMBER(2),
    punkty_kategorii   NUMBER(2),
    pozycja_kategoria  NUMBER(3),
    pozycja_globalnie  NUMBER(3),
    lokata_w_biegu     NUMBER(3) NOT NULL
);

CREATE UNIQUE INDEX pk_bd3_wyniki ON
    bd3_wyniki (nr_zawodow, nr_zawodnika);

ALTER TABLE bd3_wyniki
    ADD CONSTRAINT pk_bd3_wyniki PRIMARY KEY ( nr_zawodow,
                                               nr_zawodnika )
        USING INDEX pk_bd3_wyniki;

CREATE TABLE bd3_zawodnicy (
    nr_zawodnika    NUMBER(4) NOT NULL,
    nr_klubu        NUMBER(3),
    nr_kategorii    NUMBER(2) NOT NULL,
    imie            VARCHAR2(15),
    nazwisko        VARCHAR2(25) NOT NULL,
    plec            CHAR(1) NOT NULL,
    data_urodzenia  DATE NOT NULL
);

ALTER TABLE bd3_zawodnicy
    ADD CONSTRAINT ch_bd3_zawodnicy_plec CHECK ( plec IN ( 'K', 'M' ) );

CREATE UNIQUE INDEX pk_bd3_zawodnicy ON
    bd3_zawodnicy (nr_zawodnika);

ALTER TABLE bd3_zawodnicy
    ADD CONSTRAINT pk_bd3_zawodnicy PRIMARY KEY ( nr_zawodnika )
        USING INDEX pk_bd3_zawodnicy;

CREATE TABLE bd3_zawody (
    nr_zawodow     NUMBER(2) NOT NULL,
    nazwa_zawodow  VARCHAR2(40) NOT NULL,
    data_zawodow   DATE,
    podtytul       VARCHAR2(70)
);

CREATE UNIQUE INDEX pk_bd3_zawody ON
    bd3_zawody (nr_zawodow);

ALTER TABLE bd3_zawody
    ADD CONSTRAINT pk_bd3_zawody PRIMARY KEY ( nr_zawodow )
        USING INDEX pk_bd3_zawody;

ALTER TABLE bd3_zawodnicy
    ADD CONSTRAINT fk_bd3_kategorie_bd3_zawodnicy FOREIGN KEY ( nr_kategorii )
        REFERENCES bd3_kategorie ( nr_kategorii );

ALTER TABLE bd3_zawodnicy
    ADD CONSTRAINT fk_bd3_kluby_bd3_zawodnicy FOREIGN KEY ( nr_klubu )
        REFERENCES bd3_kluby ( nr_klubu );

ALTER TABLE bd3_wyniki
    ADD CONSTRAINT fk_bd3_zawodnicy_bd3_wyniki FOREIGN KEY ( nr_zawodnika )
        REFERENCES bd3_zawodnicy ( nr_zawodnika );

ALTER TABLE bd3_wyniki
    ADD CONSTRAINT fk_bd3_zawody_bd3_wyniki FOREIGN KEY ( nr_zawodow )
        REFERENCES bd3_zawody ( nr_zawodow );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             5
-- ALTER TABLE                             10
